using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.StationJobSlots;

[GenerateTypedNameReferences]
public sealed partial class StationJobSlotsWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    public event Action<NetEntity, ProtoId<JobPrototype>, StationJobSlotOperation, int?>? OnSlotChange;

    private StationJobSlotsData[] _stations = [];
    private NetEntity? _station;
    private ProtoId<DepartmentPrototype>? _department;
    private readonly List<(ProtoId<JobPrototype> Job, StationJobSlotRow Control)> _rows = [];

    public StationJobSlotsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        DepartmentSelector.OptionStyleClasses.Add(StyleClass.ButtonOpenBoth);

        StationSelector.OnItemSelected += args =>
        {
            StationSelector.SelectId(args.Id);
            _station = _stations[args.Id].Station;
            RefreshJobs();
        };

        DepartmentSelector.OnItemSelected += args =>
        {
            DepartmentSelector.SelectId(args.Id);
            _department = (ProtoId<DepartmentPrototype>?)DepartmentSelector.SelectedMetadata;
            RefreshJobs();
        };

        AddJobSelector.OnItemSelected += args =>
        {
            var item = AddJobSelector.GetItemMetadata(AddJobSelector.GetIdx(args.Id));
            if (_station is { } station && item is ProtoId<JobPrototype> job)
                OnSlotChange?.Invoke(station, job, StationJobSlotOperation.Add, null);
        };

        JobsContainer.OnResized += UpdateHeaderMargin;
        JobsScroll.OnResized += UpdateHeaderMargin;
        RefreshDepartments();
        RefreshAddJobs([]);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _prototypes.PrototypesReloaded += OnPrototypesReloaded;
    }

    protected override void ExitedTree()
    {
        _prototypes.PrototypesReloaded -= OnPrototypesReloaded;
        base.ExitedTree();
    }

    private void OnPrototypesReloaded(PrototypesReloadedEventArgs args)
    {
        RefreshDepartments();
        RefreshJobs();
    }

    private void UpdateHeaderMargin() =>
        HeaderLayout.Margin = new Thickness(0, 0, Math.Max(0, JobsScroll.Width - JobsContainer.Width), 0);

    public void UpdateStations(StationJobSlotsData[] stations)
    {
        var previousStations = _stations;
        var previous = previousStations.FirstOrDefault(station => station.Station == _station);
        _stations = stations;
        RefreshStations(previousStations);
        var current = _stations.FirstOrDefault(station => station.Station == _station);
        if (previous is null || current is null || previous.Station != current.Station ||
            previous.Weights != current.Weights || previous.Slots.Count != current.Slots.Count ||
            previous.Slots.Keys.Any(job => !current.Slots.ContainsKey(job)))
        {
            RefreshJobs();
            return;
        }

        foreach (var (job, row) in _rows)
        {
            row.UpdateSlots(current.Slots[job]);
        }
    }

    private void RefreshStations(StationJobSlotsData[] previous)
    {
        if (StationSelector.ItemCount > 0 && _stations.Select(station => (station.Station, station.Name))
            .SequenceEqual(previous.Select(station => (station.Station, station.Name))))
            return;

        StationSelector.Clear();
        StationSelector.Disabled = _stations.Length == 0;

        if (_stations.Length == 0)
        {
            _station = null;
            StationSelector.AddItem(Loc.GetString("admin-station-job-slots-no-stations"));
            return;
        }

        foreach (var station in _stations)
        {
            StationSelector.AddItem(station.Name);
        }

        var selected = Math.Max(0, Array.FindIndex(_stations, station => station.Station == _station));
        _station = _stations[selected].Station;
        StationSelector.SelectId(selected);
    }

    private void RefreshDepartments()
    {
        var departments = _prototypes.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .OrderBy(department => department, DepartmentUIComparer.Instance);

        DepartmentSelector.Clear();
        DepartmentSelector.AddItem(Loc.GetString("admin-station-job-slots-all-departments"));

        foreach (var department in departments)
        {
            var id = DepartmentSelector.ItemCount;
            DepartmentSelector.AddItem(Loc.GetString(department.Name));
            DepartmentSelector.SetItemMetadata(id, (ProtoId<DepartmentPrototype>)department.ID);
            if (department.ID == _department)
                DepartmentSelector.SelectId(id);
        }

        _department = (ProtoId<DepartmentPrototype>?)DepartmentSelector.SelectedMetadata;
    }

    private void RefreshJobs()
    {
        var station = _stations.FirstOrDefault(station => station.Station == _station);
        var slots = station?.Slots ?? [];
        var jobs = station is null ? [] : GetSortedJobs(station.Weights);

        UpdateRows(jobs.Where(job => slots.ContainsKey(job.ID)).ToArray(), slots);
        RefreshAddJobs(jobs.Where(job => !slots.ContainsKey(job.ID)).ToArray());
        EmptyState.Text = Loc.GetString(station is null
            ? "admin-station-job-slots-no-stations"
            : "admin-station-job-slots-no-jobs");
    }

    private void UpdateRows(JobPrototype[] jobs, Dictionary<ProtoId<JobPrototype>, int?> slots)
    {
        JobsContainer.RemoveAllChildren();
        _rows.Clear();
        var sprites = _entities.System<SpriteSystem>();
        var station = _station;
        for (var i = 0; i < jobs.Length; i++)
        {
            var job = jobs[i];
            var texture = _prototypes.TryIndex(job.Icon, out var icon) ? sprites.Frame0(icon.Icon) : null;
            var row = new StationJobSlotRow();
            row.UpdateJob(job.LocalizedName, texture, i % 2 != 0);
            row.UpdateSlots(slots[job.ID]);
            row.OnSlotChange += (operation, value) =>
            {
                if (station is { } selected)
                    OnSlotChange?.Invoke(selected, job.ID, operation, value);
            };
            _rows.Add((job.ID, row));
            JobsContainer.AddChild(row);
        }

        EmptyState.Visible = jobs.Length == 0;
        JobsScroll.Visible = jobs.Length > 0;
    }

    private JobPrototype[] GetSortedJobs(ProtoId<JobWeightPrototype>? weights)
    {
        var jobs = _prototypes.EnumeratePrototypes<JobPrototype>();
        if (_department is { } id && _prototypes.TryIndex(id, out var department))
            jobs = jobs.Where(job => department.Roles.Contains(job.ID));

        if (!JobUIComparer.TryCreate(_prototypes, weights, out var comparer))
            return jobs.OrderBy(job => job.LocalizedName, StringComparer.CurrentCulture).ToArray();

        return jobs.OrderBy(job => job, comparer)
            .ThenBy(job => job.LocalizedName, StringComparer.CurrentCulture)
            .ToArray();
    }

    private void RefreshAddJobs(JobPrototype[] jobs)
    {
        AddJobSelector.Disabled = _station is null || jobs.Length == 0;
        AddJobSelector.Clear();
        AddJobSelector.AddItem(Loc.GetString("admin-station-job-slots-add"));
        AddJobSelector.SetItemDisabled(0, true);
        foreach (var job in jobs)
        {
            var id = AddJobSelector.ItemCount;
            AddJobSelector.AddItem(job.LocalizedName);
            AddJobSelector.SetItemMetadata(id, (ProtoId<JobPrototype>)job.ID);
        }
    }
}
