using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.StationJobSlots;

[GenerateTypedNameReferences]
public sealed partial class StationJobSlotsWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entities = default!;

    public event Action<NetEntity, ProtoId<JobPrototype>, StationJobSlotOperation>? OnSlotChangeRequested;

    private StationJobSlotsData[] _stations = [];
    private NetEntity? _selectedStation;
    private ProtoId<DepartmentPrototype>? _selectedDepartment;
    private readonly List<(NetEntity Station, string Name)> _stationOptions = [];
    private ProtoId<DepartmentPrototype>[] _departments = [];
    private ProtoId<JobPrototype>[] _visibleJobs = [];
    private ProtoId<JobPrototype>[] _addableJobs = [];
    private readonly Dictionary<ProtoId<JobPrototype>, StationJobSlotRow> _rows = [];

    public StationJobSlotsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StationSelector.OnItemSelected += args =>
        {
            StationSelector.SelectId(args.Id);
            _selectedStation = _stationOptions[args.Id].Station;
            RefreshJobs();
        };
        DepartmentSelector.OnItemSelected += args =>
        {
            DepartmentSelector.SelectId(args.Id);
            _selectedDepartment = args.Id == 0 ? null : (ProtoId<DepartmentPrototype>?) _departments[args.Id - 1];
            RefreshJobs();
        };
        AddJobSelector.OnItemSelected += args =>
        {
            if (_selectedStation is not { } station || args.Id == 0)
                return;

            var job = _addableJobs[args.Id - 1];
            AddJobSelector.SelectId(0);
            OnSlotChangeRequested?.Invoke(station, job, StationJobSlotOperation.Add);
        };

        JobsContainer.OnResized += UpdateHeaderMargin;
        JobsScroll.OnResized += UpdateHeaderMargin;
        RefreshDepartments();
        RefreshAddJobs([]);
    }

    private void UpdateHeaderMargin()
    {
        HeaderLayout.Margin = new Thickness(0, 0, Math.Max(0, JobsScroll.Width - JobsContainer.Width), 0);
    }

    public void UpdateStations(StationJobSlotsData[] stations)
    {
        _stations = stations;
        RefreshStations();
        RefreshJobs();
    }

    private void RefreshStations()
    {
        var stations = _stations.Select(station => (station.Station, station.StationName)).ToArray();
        if (_stationOptions.SequenceEqual(stations) && StationSelector.ItemCount > 0)
            return;

        _stationOptions.Clear();
        _stationOptions.AddRange(stations);
        StationSelector.Clear();
        StationSelector.Disabled = stations.Length == 0;
        if (stations.Length == 0)
        {
            _selectedStation = null;
            StationSelector.AddItem(Loc.GetString("admin-station-job-slots-no-stations"));
            return;
        }

        for (var i = 0; i < stations.Length; i++)
            StationSelector.AddItem(stations[i].StationName, i);

        var selected = _stationOptions.FindIndex(station => station.Station == _selectedStation);
        if (selected < 0)
            selected = 0;
        _selectedStation = _stationOptions[selected].Station;
        StationSelector.SelectId(selected);
    }

    private void RefreshDepartments()
    {
        var departments = _prototypes.EnumeratePrototypes<DepartmentPrototype>()
            .OrderBy(department => department, DepartmentUIComparer.Instance).ToArray();
        _departments = departments.Select(department => (ProtoId<DepartmentPrototype>) department.ID).ToArray();
        DepartmentSelector.Clear();
        DepartmentSelector.AddItem(Loc.GetString("admin-station-job-slots-all-departments"), 0);
        for (var i = 0; i < _departments.Length; i++)
            DepartmentSelector.AddItem(Loc.GetString(departments[i].Name), i + 1);

        var selected = Array.FindIndex(_departments, department => department == _selectedDepartment);
        DepartmentSelector.SelectId(selected + 1);
        if (selected < 0)
            _selectedDepartment = null;
    }

    private void RefreshJobs()
    {
        var station = _stations.FirstOrDefault(station => station.Station == _selectedStation);
        var jobs = station == null ? [] : GetSortedJobs(station.JobWeights);
        var stationJobs = station == null
            ? []
            : jobs.Where(job => station.JobSlots.ContainsKey(job.ID)).ToArray();
        var addableJobs = station == null
            ? []
            : jobs.Where(job => !station.JobSlots.ContainsKey(job.ID)).ToArray();

        UpdateRows(stationJobs, station?.JobSlots ?? []);
        RefreshAddJobs(addableJobs);
        EmptyState.Text = Loc.GetString(station == null
            ? "admin-station-job-slots-no-stations"
            : "admin-station-job-slots-no-jobs");
    }

    private void UpdateRows(JobPrototype[] jobs, Dictionary<ProtoId<JobPrototype>, int?> slots)
    {
        var ids = jobs.Select(job => (ProtoId<JobPrototype>) job.ID).ToArray();

        if (!_visibleJobs.SequenceEqual(ids))
        {
            _visibleJobs = ids;
            JobsContainer.RemoveAllChildren();
            _rows.Clear();
            foreach (var id in ids)
            {
                var row = new StationJobSlotRow();
                row.OnSlotChangeRequested += operation =>
                {
                    if (_selectedStation is { } station)
                        OnSlotChangeRequested?.Invoke(station, id, operation);
                };
                _rows.Add(id, row);
                JobsContainer.AddChild(row);
            }
        }

        var sprites = _entities.System<SpriteSystem>();
        for (var i = 0; i < jobs.Length; i++)
        {
            var job = jobs[i];
            var texture = _prototypes.TryIndex(job.Icon, out var icon) ? sprites.Frame0(icon.Icon) : null;
            _rows[job.ID].UpdateJob(job.LocalizedName, texture, slots[job.ID], i % 2 != 0);
        }

        EmptyState.Visible = jobs.Length == 0;
        JobsScroll.Visible = jobs.Length > 0;
    }

    private bool InSelectedDepartment(ProtoId<JobPrototype> job)
    {
        return _selectedDepartment == null ||
               _prototypes.TryIndex(_selectedDepartment.Value, out var department) && department.Roles.Contains(job);
    }

    private JobPrototype[] GetSortedJobs(ProtoId<JobWeightPrototype>? weights)
    {
        var jobs = _prototypes.EnumeratePrototypes<JobPrototype>()
            .Where(job => InSelectedDepartment(job.ID))
            .OrderBy(job => job.LocalizedName, StringComparer.CurrentCulture);

        return JobUIComparer.TryCreate(_prototypes, weights, out var comparer)
            ? jobs.OrderBy(job => job, comparer).ToArray()
            : jobs.ToArray();
    }

    private void RefreshAddJobs(JobPrototype[] jobs)
    {
        AddJobSelector.Disabled = _selectedStation == null || jobs.Length == 0;
        var ids = jobs.Select(job => (ProtoId<JobPrototype>) job.ID).ToArray();
        if (_addableJobs.SequenceEqual(ids) && AddJobSelector.ItemCount > 0)
            return;

        _addableJobs = ids;
        AddJobSelector.Clear();
        AddJobSelector.AddItem(Loc.GetString("admin-station-job-slots-add"), 0);
        AddJobSelector.SetItemDisabled(0, true);
        for (var i = 0; i < jobs.Length; i++)
        {
            AddJobSelector.AddItem(jobs[i].LocalizedName, i + 1);
        }

        AddJobSelector.SelectId(0);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _prototypes.PrototypesReloaded += OnPrototypesReloaded;
    }

    protected override void ExitedTree()
    {
        _prototypes.PrototypesReloaded -= OnPrototypesReloaded;
        base.ExitedTree();
    }

    private void OnPrototypesReloaded(PrototypesReloadedEventArgs args)
    {
        RefreshDepartments();
        _addableJobs = [];
        AddJobSelector.Clear();
        RefreshJobs();
    }
}
