using Content.Client.Stylesheets;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.StationJobSlots;

[GenerateTypedNameReferences]
public sealed partial class StationJobSlotRow : PanelContainer
{
    public const float SlotsWidth = 120;
    public const float ButtonWidth = 32;

    public event Action<StationJobSlotOperation, int?>? OnSlotChange;

    private int? _slots;
    private bool _editing;
    private bool _modified;
    private bool _toggling;

    public StationJobSlotRow()
    {
        RobustXamlLoader.Load(this);
        SlotCount.IsValid = value => value >= 0;
        SlotCount.InitDefaultButtons();
        SlotCount.LineEditControl.IsValid = text => text.Length == 0 || int.TryParse(text, out var value) && value >= 0;
        SlotCount.LineEditControl.OnFocusEnter += _ => _editing = true;
        SlotCount.LineEditControl.OnTextChanged += _ => _editing = _modified = true;
        SlotCount.LineEditControl.OnTextEntered += _ => ApplySlotCount();
        SlotCount.LineEditControl.OnFocusExit += _ => ApplySlotCount();
        SlotCount.ValueChanged += args =>
        {
            if (SlotCount.LineEditDisabled || args.Value < 0 || args.Value != SlotCount.Value)
                return;

            _editing = _modified = true;
            if (!SlotCount.LineEditControl.HasKeyboardFocus())
                ApplySlotCount();
        };

        UnlimitedButton.OnToggled += args =>
        {
            _editing = false;
            _toggling = true;
            UpdateControls();
            OnSlotChange?.Invoke(args.Pressed ? StationJobSlotOperation.Set : StationJobSlotOperation.Restore, null);
        };
        UnlimitedButton.OnMouseExited += _ =>
        {
            if (!_toggling)
                return;

            _toggling = false;
            UpdateSlots(_slots);
        };
        RemoveButton.OnPressed += _ =>
        {
            CancelEdit();
            OnSlotChange?.Invoke(StationJobSlotOperation.Remove, null);
        };
    }

    protected override void ExitedTree()
    {
        CancelEdit();
        base.ExitedTree();
    }

    public void UpdateJob(string name, Texture? icon, bool alternate)
    {
        SetOnlyStyleClass(alternate ? StyleClass.PanelLight : StyleClass.PanelDark);
        JobName.Text = name;
        JobName.ToolTip = name;
        JobIcon.Texture = icon;
    }

    public void UpdateSlots(int? slots)
    {
        _slots = slots;
        if (_editing)
            return;

        if (!_toggling)
            UnlimitedButton.Pressed = slots is null;
        UpdateControls();
    }

    private void UpdateControls()
    {
        var unlimited = UnlimitedButton.Pressed;
        if (unlimited)
            CancelEdit();

        SlotCount.LineEditDisabled = unlimited;
        SlotCount.LineEditControl.CanKeyboardFocus = !unlimited;
        SlotCount.SetButtonDisabled(unlimited);
        SlotCount.OverrideValue(_slots ?? 0);
        UnlimitedButton.ToolTip = Loc.GetString(unlimited
            ? "admin-station-job-slots-limited-tooltip"
            : "admin-station-job-slots-unlimited-tooltip");
    }

    private void ApplySlotCount()
    {
        if (!_editing)
            return;

        _editing = false;

        if (_modified && !SlotCount.LineEditDisabled &&
            int.TryParse(SlotCount.LineEditControl.Text, out var value) && value >= 0)
            OnSlotChange?.Invoke(StationJobSlotOperation.Set, value);
        else
            UpdateSlots(_slots);
        _modified = false;
    }

    private void CancelEdit()
    {
        _editing = _modified = false;
        SlotCount.LineEditControl.ReleaseKeyboardFocus();
    }
}
