using Content.Client.Stylesheets;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.StationJobSlots;

[GenerateTypedNameReferences]
public sealed partial class StationJobSlotRow : PanelContainer
{
    public event Action<StationJobSlotOperation>? OnSlotChangeRequested;
    private int? _freeSlots;

    public StationJobSlotRow()
    {
        RobustXamlLoader.Load(this);
        DecreaseButton.OnPressed += _ => OnSlotChangeRequested?.Invoke(StationJobSlotOperation.Decrease);
        IncreaseButton.OnPressed += _ => OnSlotChangeRequested?.Invoke(StationJobSlotOperation.Increase);
        UnlimitedButton.OnPressed += _ => OnSlotChangeRequested?.Invoke(_freeSlots is null
            ? StationJobSlotOperation.MakeLimited
            : StationJobSlotOperation.MakeUnlimited);
    }

    public void UpdateJob(string name, Texture? icon, int? slots, bool alternate)
    {
        _freeSlots = slots;
        SetOnlyStyleClass(alternate ? StyleClass.PanelLight : StyleClass.PanelDark);
        JobName.Text = name;
        JobName.ToolTip = name;
        JobIcon.Texture = icon;
        SlotCount.Text = slots?.ToString() ?? Loc.GetString("admin-station-job-slots-unlimited");
        DecreaseButton.Disabled = slots is null or <= 0;
        IncreaseButton.Disabled = slots is null or int.MaxValue;
        UnlimitedButton.Pressed = slots is null;
        UnlimitedButton.ToolTip = Loc.GetString(slots is null
            ? "admin-station-job-slots-limited-tooltip"
            : "admin-station-job-slots-unlimited-tooltip");
    }
}
